// Dev-only JSX tagger for the Forcey Magic editor (plans/08 in the platform monorepo).
// Stamps every JSX element in project source with `data-forcey-id="<file>:<line>:<column>"`,
// the location of its opening `<`, so the editor can map a DOM node back to the JSX that
// rendered it. Platform code: it lives in .forcey/, loaded only by .forcey/vite.config.ts in a
// sandbox, so it never reaches a project, its export or its published build.
//
// Attributes are inserted with magic-string rather than re-printing the AST, so the code the
// project's own plugins see is byte-for-byte the source plus the attribute, and the source map
// stays exact. The plugin must run before every other transform (`enforce: 'pre'`, and first in
// the plugin list): TanStack Router's route splitter rewrites route modules, and positions taken
// after it would no longer point at the file the user (and the agent) can open.
import { parse } from '@babel/parser';
import MagicString from 'magic-string';
import { posix, relative, sep } from 'node:path';
import type { Plugin } from 'vite';

export const TAG_ATTRIBUTE = 'data-forcey-id';

const SOURCE_FILE = /\.[jt]sx$/;

const isFragment = (name: string) => name === 'Fragment' || name === 'React.Fragment';

type NameNode = { type: string; name?: unknown; object?: NameNode; property?: NameNode };

const elementName = (node: NameNode): string => {
  if (node.type === 'JSXIdentifier' && typeof node.name === 'string') return node.name;
  if (node.type === 'JSXMemberExpression' && node.object && node.property)
    return `${elementName(node.object)}.${elementName(node.property)}`;
  return '';
};

type Walkable = { type?: string; [key: string]: unknown };

// A plain recursive walk: the tagger needs one node type, not a traversal framework.
const visit = (node: unknown, onOpening: (element: Walkable) => void) => {
  if (!node || typeof node !== 'object') return;
  if (Array.isArray(node)) {
    for (const child of node) visit(child, onOpening);
    return;
  }
  const current = node as Walkable;
  if (current.type === 'JSXOpeningElement') onOpening(current);
  for (const [key, value] of Object.entries(current)) {
    if (key === 'loc' || key === 'start' || key === 'end' || key === 'extra') continue;
    visit(value, onOpening);
  }
};

export function forceyTagger(): Plugin {
  let root = process.cwd();

  return {
    name: 'forcey-tagger',
    enforce: 'pre',
    apply: 'serve',

    configResolved(config) {
      root = config.root;
    },

    transform(code, id) {
      const file = id.replace(/\?.*$/, '');
      if (!SOURCE_FILE.test(file) || file.includes('/node_modules/')) return null;
      const relativePath = relative(root, file).split(sep).join(posix.sep);
      // Only the project's own source is editable; anything outside src/ is not tagged.
      if (relativePath.startsWith('..') || !relativePath.startsWith('src/')) return null;
      // Generated by the router plugin, never edited by hand or by the agent.
      if (relativePath.endsWith('routeTree.gen.ts') || relativePath.endsWith('routeTree.gen.tsx'))
        return null;

      let ast: unknown;
      try {
        ast = parse(code, { sourceType: 'module', plugins: ['jsx', 'typescript'] });
      } catch {
        // A file that does not parse is the compiler's error to report, not the tagger's.
        return null;
      }

      const output = new MagicString(code);
      let tagged = 0;
      visit(ast, (element) => {
        const name = element.name as (NameNode & { end?: number }) | undefined;
        const start = element.start as number | undefined;
        const loc = element.loc as { start: { line: number; column: number } } | undefined;
        const attributes = element.attributes as { name?: { name?: unknown } }[] | undefined;
        if (!name || typeof name.end !== 'number' || start === undefined || !loc) return;
        if (isFragment(elementName(name))) return;
        if (attributes?.some((a) => a.name?.name === TAG_ATTRIBUTE)) return;
        output.appendLeft(
          name.end,
          ` ${TAG_ATTRIBUTE}="${relativePath}:${loc.start.line}:${loc.start.column + 1}"`
        );
        tagged++;
      });

      if (tagged === 0) return null;
      return {
        code: output.toString(),
        map: output.generateMap({ hires: true, source: file }).toString()
      };
    }
  };
}
